export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/v1/auth/login',
    REGISTER: '/v1/auth/register',
    LOGOUT: '/v1/auth/logout',
    REFRESH_TOKEN: '/v1/auth/refresh',
    VERIFY_EMAIL: '/v1/auth/verify-email',
    FORGOT_PASSWORD: '/v1/auth/forgot-password',
    RESET_PASSWORD: '/v1/auth/reset-password',
    ME: '/v1/auth/me',
  },
  USERS: {
    PROFILE: '/v1/auth/me',
    UPDATE_PROFILE: '/v1/auth/me',
    CHANGE_PASSWORD: '/v1/auth/change-password',
  },
  PROJECTS: {
    BASE: '/v1/projects',
    DETAIL: (id) => `/v1/projects/${id}`,
    MEMBERS: {
      LIST: (id) => `/v1/projects/${id}/team`,
      ADD: (id) => `/v1/projects/${id}/team`,
      UPDATE: (projectId, userId) => `/v1/projects/${projectId}/team/${userId}`,
      REMOVE: (projectId, userId) => `/v1/projects/${projectId}/team/${userId}`,
    },
  },
  BOARDS: {
    LIST: (projectId) => `/v1/projects/${projectId}/boards`,
    DETAIL: (id) => `/v1/boards/${id}`,
    CREATE: (projectId) => `/v1/projects/${projectId}/boards`,
    UPDATE: (id) => `/v1/boards/${id}`,
    DELETE: (id) => `/v1/boards/${id}`,
  },
  SPRINTS: {
    LIST: (boardId) => `/v1/boards/${boardId}/sprints`,
    CREATE: (boardId) => `/v1/boards/${boardId}/sprints`,
    START: (id) => `/v1/sprints/${id}/start`,
    COMPLETE: (id) => `/v1/sprints/${id}/complete`,
  },
  ISSUES: {
    LIST: (boardId) => `/v1/boards/${boardId}/issues`,
    DETAIL: (id) => `/v1/issues/${id}`,
    CREATE: (boardId) => `/v1/boards/${boardId}/issues`,
    UPDATE: (id) => `/v1/issues/${id}`,
    DELETE: (id) => `/v1/issues/${id}`,
    COMMENTS: {
      LIST: (issueId) => `/v1/issues/${issueId}/comments`,
      CREATE: (issueId) => `/v1/issues/${issueId}/comments`,
      UPDATE: (id) => `/v1/comments/${id}`,
      DELETE: (id) => `/v1/comments/${id}`,
    },
    TIME_LOGS: {
      LIST: (issueId) => `/v1/issues/${issueId}/time-logs`,
      CREATE: (issueId) => `/v1/issues/${issueId}/time-logs`,
      UPDATE: (id) => `/v1/time-logs/${id}`,
      DELETE: (id) => `/v1/time-logs/${id}`,
    },
  },
  AI: {
    SPRINT_PLANNING: (projectId) => `/v1/projects/${projectId}/ai/sprint-planning`,
    SCOPE_CREEP: (projectId) => `/v1/projects/${projectId}/ai/scope-creep-detection`,
    RISK_ASSESSMENT: (projectId) => `/v1/projects/${projectId}/ai/risk-assessment`,
    RETROSPECTIVE: (projectId) => `/v1/projects/${projectId}/ai/retrospective`,
    QUOTA: (projectId) => `/v1/projects/${projectId}/ai/quota`,
  },
};